name: Matrix flow
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12,13,14]
        operating-system: [ubuntu-latest, window-latest]        
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3  
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
